name: My workflow
run-name: ${{github.actor }} is testing out github actions
on: push

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name : Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up flake 8
        uses: py-actions/flake8@v2
        with:
          ignore: "F401"
          exclude: "src/ignoreme.py"
          max-line-length: "100"
          path: "src"
          plugins: "flake8-bugbear==22.1.11 flake8-black"
      - name: Tests with nose
        run : | 
          pip install nose nosetests
