name : My workflow
run-name: ${{github.actor }} is testing out github actions
on: push

jobs:
  build :
    runs-on : [ubuntu-latest]
    steps :
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
